---
title: "Tracking_GAM_LMB"
author: "Lauren M Baggett"
date: "2024-04-18"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## LMB 04/18/2024
# This script will create a model for group size at SOCAL tracking sites.

```{r settings setup}
# load relevent packages
library(mgcv)
library(splus2R)
library(car)
library(FSA)

# read in data
df = read.csv("F:/Tracking/groups/SOCAL_total_binned_groups.csv")

```

# check for autocorrelation

```{r autocorrelation test, echo=FALSE}

# check autocorrelation factor
df$groupSize = as.numeric(df$groupSize)

# make a histogram to show the distribution
hist(df$groupSize)

myACF = acf(df$groupSize, na.action = na.pass)
# never passes below the blue line :( now run a GLM

glmod1 = glm(df$groupSize~df$dayNight+df$jd+df$site, family=poisson)
summary(glmod1)
# check acf on the residuals
all_acf = acf(residuals(glmod1),300)

sig = qnorm((1+0.95)/2)/sqrt(sum(!is.na(residuals(glmod1))))
sig
idx = which(all_acf$acf < sig)[1]
all_acf$lag[idx]

```

``` {r site W remove zeros, echo=TRUE}

# replace the zeros with Nas....this changes the question that we're asking here.
# during times in which we track whales, are we

# replace zeros with Nas just to give it a go
zeros = which(df$groupSize==0)
df$groupSize[zeros] = NA

newACF = acf(df$groupSize, na.action = na.pass)

df$groupSize = as.numeric(df$groupSize)

glmod1 = glm(df$groupSize~df$dayNight+df$jd+df$site, family=poisson)
summary(glmod1)
# check acf on the residuals
all_acf = acf(residuals(glmod1),300)

sig = qnorm((1+0.95)/2)/sqrt(sum(!is.na(residuals(glmod1))))
sig
idx = which(all_acf$acf < sig)[1]
all_acf$lag[idx]


```
```{r rebinned, echo=TRUE}
# rebin to match the earlier lag value

df = read.csv("F:/Tracking/groups/SOCAL_total_binned_260min_groups.csv")

# replace zeros with Nas just to give it a go
zeros = which(df$groupSize==0)
df$groupSize[zeros] = NA

dfMod = df[-which(is.na(df$groupSize)),]
dfMod$jd = as.numeric(dfMod$jd)
dfMod$dayNight = as.factor(dfMod$dayNight)
dfMod$site = as.factor(dfMod$site)
dfMod$presBins = as.numeric(dfMod$presBins)

# check to see if anything is collinear
lm1 = lm(groupSize~jd+presBins,data=dfMod)
car::vif(lm1)
#       jd presBins 
# 1.018179 1.018179
# this is looking good, move on

# check whether presence bins should be linear or a smooth
m1 = gam(groupSize~presBins,data=dfMod,family=tw(),method='REML')
m2 = gam(groupSize~s(presBins,bs='ts'),data=dfMod,family=tw(),method='REML')
aic1 = AIC(m1)
aic2 = AIC(m2)

# test to make sure isn't normal
shapiro.test(dfMod$groupSize)
# 	Shapiro-Wilk normality test
# 
# data:  dfMod$groupSize
# W = 0.8379, p-value < 2.2e-16

fullModel = gam(groupSize~
                  + s(dfMod$jd,bs='cc')
                  + dayNight
                  + s(presBins,bs='ts')
                  + site,
                data=dfMod,family=tw(),method='REML')

selectedCovariates = c("s(jd,bs='cc')", "dayNight","s(presBins,bs='ts')", "site")
namesCovariates = c("jd","daynight","pres","site")
iVarList = 1:length(selectedCovariates)
NVars = length(selectedCovariates)

# Backward selection:
# to start, you are running a full model with all non-collinear variables.
# then, the for loop runs the gams, removing a single variable (going through each potential one)
# look at the model with the lowest AIC-what variable was removed?
# branch off from there, run the for loop again, removing another variable (going through each one)
# keep doing this as long as the AIC value continues to decrease
# once AIC is increasing, go back to the last set of models run and select the last model ran
# "Removed"=variable(s) not included in the model
# "Idx" = variables included in the model
# ------------------------------------------------------------------------------
backSelection1 = matrix(0, ncol=3, nrow=NVars+1)
colnames(backSelection1) = c("Removed","Idx Vars", "AIC")
# 1st full model
backSelection1[NVars+1,1] = "None excluded"
backSelection1[NVars+1,2] = paste(iVarList,collapse=" ")
backSelection1[NVars+1,3] = AIC(fullModel)

# Remove one variable at a time
for (x in 1: length (selectedCovariates)){
  gc()
  iselected = iVarList[-c(x)]
  iselected = iselected[order(iselected,decreasing = FALSE)]
  newformula = as.formula(paste("groupSize ~", paste(selectedCovariates[iselected], collapse = " + ")))
  m = gam(as.formula (newformula),data=dfMod,family=tw(),method="REML") 
  backSelection1[x,1] = namesCovariates[x]
  backSelection1[x,2] = paste(iselected,collapse=" ")
  backSelection1[x,3] = AIC(m)
}
backSelection1[order(backSelection1[,3],decreasing=FALSE),]
#      Removed         Idx Vars  AIC               
# [1,] "daynight"      "1 3 4"   "7273.88561130768"
# [2,] "None excluded" "1 2 3 4" "7279.71497731162"
# [3,] "jd"            "2 3 4"   "7284.57341949811"
# [4,] "site"          "1 2 3"   "7288.77865228618"
# [5,] "pres"          "1 2 4"   "7361.21909667489"

# 2nd Round
varExcluded = c(2) # choose variable (number) that had the lowest AIC (top), if is none excluded than stop 
                   #(this means not removing another variable was the most descriptive model)
backSelection2 = matrix(0, ncol=3, nrow=NVars-length(varExcluded))
colnames(backSelection2) = c("Removed","Idx Vars", "AIC")
# exclude one variable at a time
i = 1
for (x in 1: length (selectedCovariates)){
  if (all(x != varExcluded)){
    gc()
    iselected = iVarList[-c(x,varExcluded)]
    iselected = iselected[order(iselected,decreasing = FALSE)]
    newformula = as.formula(paste("groupSize ~", paste(selectedCovariates[iselected], collapse = " + ")))
    m = gam(as.formula (newformula),data=dfMod, family=tw(),method="REML") 
    backSelection2[i,1] = paste(namesCovariates[c(x,varExcluded)],collapse=",")
    backSelection2[i,2] = paste(iselected,collapse=" ")
    backSelection2[i,3] = AIC(m)
    i= i+1
  }
}
backSelection2[order(backSelection2[,3],decreasing=FALSE),]
#      Removed         Idx Vars AIC               
# [1,] "jd,daynight"   "3 4"    "7283.59870753476"
# [2,] "site,daynight" "1 3"    "7289.29117975485"
# [3,] "pres,daynight" "1 4"    "7363.32438683061"
# none of these are smaller than the first round, pause here
     
     
# now, run it forwards
# Forward selection
# to ensure we really are testing out every potential model, work forward!
# in this case, we are building up the model, each round of the for loop we are adding an additional variable
# again, keep adding variables until the AIC of the set is increasing instead of decreasing
# "Included" = variable that was added in this round
# "Idx" = variable(s) included in the model
# ------------------------------------------------------------------------------
fwdSelection1 = matrix(0, ncol=3, nrow=NVars)
colnames(fwdSelection1) = c("Included","Idx Vars", "AIC")

## 1st round
# Include one variable at a time
for (x in 1: length (selectedCovariates)){
  gc()
  iselected = c(x)
  newformula = as.formula(paste("groupSize ~", paste(selectedCovariates[iselected], collapse = " + ")))
  m = gam(as.formula (newformula),data=dfMod,family=tw(),method="REML") 
  fwdSelection1[x,1] = namesCovariates[iselected]
  fwdSelection1[x,2] = paste(iselected,collapse=" ")
  fwdSelection1[x,3] = AIC(m)
}
fwdSelection1[order(fwdSelection1[,3],decreasing=FALSE),]
#      Included   Idx Vars AIC               
# [1,] "pres"     "3"      "7303.73090070297"
# [2,] "site"     "4"      "7384.28497900384"
# [3,] "jd"       "1"      "7422.49264171704"
# [4,] "daynight" "2"      "7445.79810513433"

## 2nd round
# Include one variable at a time with variable(s) included from previous step
varIncluded = c(3) # variable included from previous step
fwdSelection2 = matrix(0, ncol=3, nrow=NVars-length(varIncluded))
colnames(fwdSelection2) = c("Included","Idx Vars", "AIC")
i = 1
for (x in 1: length (selectedCovariates)){
  if (all(x != varIncluded)){
    gc()
    iselected = c(varIncluded,x)
    iselected = iselected[order(iselected,decreasing = FALSE)]
    newformula = as.formula(paste("groupSize ~", paste(selectedCovariates[iselected], collapse = " + ")))
    m = gam(as.formula (newformula),data=dfMod,family=tw(),method="REML") 
    fwdSelection2[i,1] = paste(namesCovariates[iselected],collapse=",")
    fwdSelection2[i,2] = paste(iselected,collapse=" ")
    fwdSelection2[i,3] = AIC(m)
    i = i+1
  }
}
fwdSelection2[order(fwdSelection2[,3],decreasing=FALSE),]
#      Included        Idx Vars AIC               
# [1,] "pres,site"     "3 4"    "7283.59870753476"
# [2,] "jd,pres"       "1 3"    "7289.29117975485"
# [3,] "daynight,pres" "2 3"    "7304.86153778352"

## 3rd round
varIncluded = c(3,4) # variable included from previous step
fwdSelection3 = matrix(0, ncol=3, nrow=NVars-length(varIncluded))
colnames(fwdSelection3) = c("Included","Idx Vars", "AIC")
i = 1
for (x in 1: length (selectedCovariates)){
  if (all(x != varIncluded)){
    gc()
    iselected = c(varIncluded,x)
    iselected = iselected[order(iselected,decreasing = FALSE)]
    newformula = as.formula(paste("groupSize ~", paste(selectedCovariates[iselected], collapse = " + ")))
    m = gam(as.formula (newformula),data=dfMod,family=tw(),method="REML") 
    fwdSelection3[i,1] = paste(namesCovariates[iselected],collapse=",")
    fwdSelection3[i,2] = paste(iselected,collapse=" ")
    fwdSelection3[i,3] = AIC(m)
    i = i+1
  }
}
fwdSelection3[order(fwdSelection3[,3],decreasing=FALSE),]
#      Included             Idx Vars AIC               
# [1,] "jd,pres,site"       "1 3 4"  "7273.88561130768"
# [2,] "daynight,pres,site" "2 3 4"  "7284.57341949811"

## 4th round
varIncluded = c(1,3,4) # variable included from previous step
fwdSelection4 = matrix(0, ncol=3, nrow=NVars-length(varIncluded))
colnames(fwdSelection3) = c("Included","Idx Vars", "AIC")
i = 1
for (x in 1: length (selectedCovariates)){
  if (all(x != varIncluded)){
    gc()
    iselected = c(varIncluded,x)
    iselected = iselected[order(iselected,decreasing = FALSE)]
    newformula = as.formula(paste("groupSize ~", paste(selectedCovariates[iselected], collapse = " + ")))
    m = gam(as.formula (newformula),data=dfMod,family=tw(),method="REML") 
    fwdSelection4[i,1] = paste(namesCovariates[iselected],collapse=",")
    fwdSelection4[i,2] = paste(iselected,collapse=" ")
    fwdSelection4[i,3] = AIC(m)
    i = i+1
  }
}
fwdSelection4[order(fwdSelection4[,3],decreasing=FALSE),]
# "jd,daynight,pres,site" "1 2 3 4"               "7279.71497731162"

# the best model is the one without day/night, only has jd pres site


# run the model that is the best <3
# stop here, run the model and see what comes out significant
# the full model has the lowest AIC
bestModel = gam(groupSize~
                  + s(dfMod$jd,bs='cc')
                  # + dayNight
                  + s(presBins,bs='ts')
                  + site,
                data=dfMod,family=tw(),method='REML')
summary(bestModel)
# Family: Tweedie(p=1.99) 
# Link function: log 
# 
# Formula:
# groupSize ~ +s(dfMod$jd, bs = "cc") + s(presBins, bs = "ts") + 
#     site
# 
# Parametric coefficients:
#              Estimate Std. Error t value Pr(>|t|)    
# (Intercept)  1.121268   0.038519  29.110  < 2e-16 ***
# siteH       -0.055387   0.046380  -1.194    0.233    
# siteN       -0.321605   0.077521  -4.149 3.49e-05 ***
# siteW        0.004648   0.045176   0.103    0.918    
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Approximate significance of smooth terms:
#               edf Ref.df      F  p-value    
# s(dfMod$jd) 4.309      8  2.197 0.000815 ***
# s(presBins) 4.121      9 11.132  < 2e-16 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# R-sq.(adj) =  0.076   Deviance explained =  9.1%
# -REML = 3648.9  Scale est. = 0.35132   n = 1954

anova(bestModel)
# Family: Tweedie(p=1.99) 
# Link function: log 
# 
# Formula:
# groupSize ~ +s(dfMod$jd, bs = "cc") + s(presBins, bs = "ts") + 
#     site
# 
# Parametric Terms:
#      df    F  p-value
# site  3 7.89 3.13e-05
# 
# Approximate significance of smooth terms:
#               edf Ref.df      F  p-value
# s(dfMod$jd) 4.309  8.000  2.197 0.000815
# s(presBins) 4.121  9.000 11.132  < 2e-16

# make the plots
plot(bestModel)

```
So the variables that ended up being significant are: Julian Day, Presence, Site
Julian day showing a trend here. Peaks in Dec/Jan, June/July.
Presence is also showing a trend here that looks mostly linear--as presence increases, so does the group sizes recorded.


```{r kruskal-wallis test on group size, echo=TRUE}
# run kruskal-wallis
# h0: there is no difference in group size per site
# h1: there is a difference in group size per site
# this should be significant based on our gam!
kruskal.test(groupSize~site, data=dfMod)
# 	Kruskal-Wallis rank sum test
# 
# data:  groupSize by site
# Kruskal-Wallis chi-squared = 51.992, df = 3, p-value = 3.007e-11

# now, a post-hoc test
dunnTest(groupSize~site, data=dfMod,
         method="bh")

# E-H same
# E-N different
# H-N different
# E-W same
# H-W different
# N-W different


```