---
title: "Tracking_GAM_perSite_LMB_siteH"
author: "Lauren M Baggett"
date: "2024-05-10"
output: html_document
---

```{r settings setup}
# load relevent packages
library(mgcv)
library(splus2R)
library(car)
library(FSA)

# read in data
df = read.csv("F:/Tracking/groups/SOCAL_H_binned_20min_groups_allVars.csv")

```

Now, make a model per site!

Site H:
```{r site H autocorrelation}

# make 0s Nas
df[which(df$groupSize==0),4] = NA

# check autocorrelation factor
df$groupSize = as.numeric(df$groupSize)
# make a histogram to show the distribution
hist(df$groupSize)

glmod1 = glm(df$groupSize~df$dayNight+df$jd,family=poisson)
summary(glmod1)
# check acf on the residuals
all_acf = acf(residuals(glmod1),300)

sig = qnorm((1+0.95)/2)/sqrt(sum(!is.na(residuals(glmod1))))
sig
idx = which(all_acf$acf < sig)[1]
all_acf$lag[idx]

```

For site H, lag is 6. 6*20 = 120 minutes. Rebin and then continute on.

```{r rebinned, echo=TRUE}
# rebin to match the earlier lag value

df = read.csv("F:/Tracking/groups/SOCAL_H_binned_120min_groups_allVars.csv")

# replace zeros with Nas just to give it a go
zeros = which(df$groupSize==0)
df$groupSize[zeros] = NA

dfMod = df[-which(is.na(df$groupSize)),]
dfMod$jd = as.numeric(dfMod$jd)
dfMod$dayNight = as.numeric(dfMod$dayNight)
dfMod$presBins = as.numeric(dfMod$presBins)

# check to see if anything is collinear
lm1 = lm(groupSize~jd+dayNight+presBins,data=dfMod)
car::vif(lm1)
#       jd dayNight presBins 
# 1.001754 1.004820 1.003216 
# not collinear, move on

# check whether presence bins should be linear or a smooth
m1 = gam(groupSize~presBins,data=dfMod,family=tw(),method='REML')
m2 = gam(groupSize~s(presBins,bs='ts'),data=dfMod,family=tw(),method='REML')
aic1 = AIC(m1)
aic2 = AIC(m2)
# linear has lower AIC

# test to make sure isn't normal
shapiro.test(dfMod$groupSize)
# 	Shapiro-Wilk normality test
# 
# data:  dfMod$groupSize
# W = 0.82116, p-value < 2.2e-16
# data isn't normal

fullModel = gam(groupSize~
                  + s(dfMod$jd,bs='cc')
                  + s(dfMod$dayNight,bs='cc')
                  + presBins,
                data=dfMod,family=tw(),method='REML')

selectedCovariates = c("s(jd,bs='cc')", "s(dayNight,bs='cc')","presBins")
namesCovariates = c("jd","daynight","pres")
iVarList = 1:length(selectedCovariates)
NVars = length(selectedCovariates)

# Backward selection:
# to start, you are running a full model with all non-collinear variables.
# then, the for loop runs the gams, removing a single variable (going through each potential one)
# look at the model with the lowest AIC-what variable was removed?
# branch off from there, run the for loop again, removing another variable (going through each one)
# keep doing this as long as the AIC value continues to decrease
# once AIC is increasing, go back to the last set of models run and select the last model ran
# "Removed"=variable(s) not included in the model
# "Idx" = variables included in the model
# ------------------------------------------------------------------------------
backSelection1 = matrix(0, ncol=3, nrow=NVars+1)
colnames(backSelection1) = c("Removed","Idx Vars", "AIC")
# 1st full model
backSelection1[NVars+1,1] = "None excluded"
backSelection1[NVars+1,2] = paste(iVarList,collapse=" ")
backSelection1[NVars+1,3] = AIC(fullModel)

# Remove one variable at a time
for (x in 1: length (selectedCovariates)){
  gc()
  iselected = iVarList[-c(x)]
  iselected = iselected[order(iselected,decreasing = FALSE)]
  newformula = as.formula(paste("groupSize ~", paste(selectedCovariates[iselected], collapse = " + ")))
  m = gam(as.formula (newformula),data=dfMod,family=tw(),method="REML") 
  backSelection1[x,1] = namesCovariates[x]
  backSelection1[x,2] = paste(iselected,collapse=" ")
  backSelection1[x,3] = AIC(m)
}
backSelection1[order(backSelection1[,3],decreasing=FALSE),]
#      Removed         Idx Vars AIC               
# [1,] "None excluded" "1 2 3"  "2017.77746750635"
# [2,] "pres"          "1 2"    "2019.33382615557"
# [3,] "daynight"      "1 3"    "2035.78868371433"
# [4,] "jd"            "2 3"    "2050.47542410732"
# lowest AIC was when none were removed, stop here

    
# now, run it forwards
# Forward selection
# to ensure we really are testing out every potential model, work forward!
# in this case, we are building up the model, each round of the for loop we are adding an additional variable
# again, keep adding variables until the AIC of the set is increasing instead of decreasing
# "Included" = variable that was added in this round
# "Idx" = variable(s) included in the model
# ------------------------------------------------------------------------------
fwdSelection1 = matrix(0, ncol=3, nrow=NVars)
colnames(fwdSelection1) = c("Included","Idx Vars", "AIC")

## 1st round
# Include one variable at a time
for (x in 1: length (selectedCovariates)){
  gc()
  iselected = c(x)
  newformula = as.formula(paste("groupSize ~", paste(selectedCovariates[iselected], collapse = " + ")))
  m = gam(as.formula (newformula),data=dfMod,family=tw(),method="REML") 
  fwdSelection1[x,1] = namesCovariates[iselected]
  fwdSelection1[x,2] = paste(iselected,collapse=" ")
  fwdSelection1[x,3] = AIC(m)
}
fwdSelection1[order(fwdSelection1[,3],decreasing=FALSE),]
#      Included   Idx Vars AIC               
# [1,] "jd"       "1"      "2037.9873911137" 
# [2,] "daynight" "2"      "2054.05932638802"
# [3,] "pres"     "3"      "2060.60856866564"
# lowest AIC is jd, add this into the model and run again

## 2nd round
# Include one variable at a time with variable(s) included from previous step
varIncluded = c(1) # variable included from previous step
fwdSelection2 = matrix(0, ncol=3, nrow=NVars-length(varIncluded))
colnames(fwdSelection2) = c("Included","Idx Vars", "AIC")
i = 1
for (x in 1: length (selectedCovariates)){
  if (all(x != varIncluded)){
    gc()
    iselected = c(varIncluded,x)
    iselected = iselected[order(iselected,decreasing = FALSE)]
    newformula = as.formula(paste("groupSize ~", paste(selectedCovariates[iselected], collapse = " + ")))
    m = gam(as.formula (newformula),data=dfMod,family=tw(),method="REML") 
    fwdSelection2[i,1] = paste(namesCovariates[iselected],collapse=",")
    fwdSelection2[i,2] = paste(iselected,collapse=" ")
    fwdSelection2[i,3] = AIC(m)
    i = i+1
  }
}
fwdSelection2[order(fwdSelection2[,3],decreasing=FALSE),]
#      Included      Idx Vars AIC               
# [1,] "jd,daynight" "1 2"    "2019.33382615557"
# [2,] "jd,pres"     "1 3"    "2035.78868371433"
# jd and dayNight have lowest AIC, add both in and proceed

## 3rd round
varIncluded = c(1,2) # variable included from previous step
fwdSelection3 = matrix(0, ncol=3, nrow=NVars-length(varIncluded))
colnames(fwdSelection3) = c("Included","Idx Vars", "AIC")
i = 1
for (x in 1: length (selectedCovariates)){
  if (all(x != varIncluded)){
    gc()
    iselected = c(varIncluded,x)
    iselected = iselected[order(iselected,decreasing = FALSE)]
    newformula = as.formula(paste("groupSize ~", paste(selectedCovariates[iselected], collapse = " + ")))
    m = gam(as.formula (newformula),data=dfMod,family=tw(),method="REML") 
    fwdSelection3[i,1] = paste(namesCovariates[iselected],collapse=",")
    fwdSelection3[i,2] = paste(iselected,collapse=" ")
    fwdSelection3[i,3] = AIC(m)
    i = i+1
  }
}
fwdSelection3[order(fwdSelection3[,3],decreasing=FALSE),]
#           Included           Idx Vars                AIC 
# "jd,daynight,pres"            "1 2 3" "2017.77746750635" 
# model all variables is best, this aligns with the backwards selection!

# run the model that is the best <3
# stop here, run the model and see what comes out significant
# the full model has the lowest AIC
bestModel = gam(groupSize~
                  + s(dfMod$jd,bs='cc')
                  + s(dfMod$dayNight,bs='cc')
                  + presBins,
                data=dfMod,family=tw(),method='REML')
summary(bestModel)
# Family: Tweedie(p=1.99) 
# Link function: log 
# 
# Formula:
# groupSize ~ +s(dfMod$jd, bs = "cc") + s(dfMod$dayNight, bs = "cc") + 
#     presBins
# 
# Parametric coefficients:
#             Estimate Std. Error t value Pr(>|t|)    
# (Intercept) 0.822161   0.034260  23.998   <2e-16 ***
# presBins    0.002949   0.001441   2.046   0.0412 *  
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Approximate significance of smooth terms:
#                     edf Ref.df     F  p-value    
# s(dfMod$jd)       5.323      8 5.183  < 2e-16 ***
# s(dfMod$dayNight) 2.792      8 2.514 3.27e-05 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# R-sq.(adj) =  0.0768   Deviance explained = 10.1%
# -REML = 1018.2  Scale est. = 0.35758   n = 607

anova(bestModel)

# Family: Tweedie(p=1.99) 
# Link function: log 
# 
# Formula:
# groupSize ~ +s(dfMod$jd, bs = "cc") + s(dfMod$dayNight, bs = "cc") + 
#     presBins
# 
# Parametric Terms:
#          df     F p-value
# presBins  1 4.186  0.0412
# 
# Approximate significance of smooth terms:
#                     edf Ref.df     F  p-value
# s(dfMod$jd)       5.323  8.000 5.183  < 2e-16
# s(dfMod$dayNight) 2.792  8.000 2.514 3.27e-05


# make the plots
plot(bestModel, all.terms=TRUE, shade = TRUE) #, residuals = F,
    # pch = 1, cex = 0.5, shift = coef(bestModel)[1])

```
These are some really exciting results! So group sizes are larger when we recorded more clicks, but this is barely significant. Some really clear seasonality here. Also a clear diel trend! Group sizes are larger at night for sure!
